/** Echo Prime SDK v3.2 — AGI module
 * Self-improving engine feedback loop — submit feedback, trigger retraining,
 * monitor learning rates, and get optimization suggestions.
 * Zero external dependencies.
 */
import { EchoHttpClient, type EchoClientConfig } from './client.js';

// ── Public interfaces ────────────────────────────────────────────────────────

/** Configuration for the AGIClient */
export interface AGIConfig {
  /** SDK Gateway base URL. Defaults to https://echo-sdk-gateway.bmcii1976.workers.dev */
  baseUrl?: string;
  /** Echo API key for authentication */
  apiKey: string;
}

/** Aggregate AGI subsystem status */
export interface AGIStatus {
  /** Total feedback submissions recorded */
  total_feedback: number;
  /** Average quality score across all feedback (0.0 - 1.0) */
  avg_quality: number;
  /** Total number of retrain jobs executed */
  total_retrains: number;
  /** Number of engines that have been improved via AGI feedback */
  engines_improved: number;
  /** ISO timestamp of the last retrain job */
  last_retrain: string;
}

/** Request to submit quality feedback for an engine */
export interface FeedbackRequest {
  /** Engine ID to submit feedback for */
  engine_id: string;
  /** The query that produced the result being evaluated (optional context) */
  query?: string;
  /** Quality score from 0.0 (terrible) to 1.0 (perfect) */
  quality_score: number;
  /** Human-readable feedback text explaining the score */
  feedback_text?: string;
}

/** Learning rate analytics across the engine fleet */
export interface LearningRate {
  /** Daily improvement rate as a percentage */
  daily_improvement: number;
  /** Weekly trend direction */
  weekly_trend: 'up' | 'down' | 'stable';
  /** Engines with the highest improvement rates */
  top_improving_engines: Array<{ engine_id: string; improvement: number }>;
  /** Engines with persistently low quality scores */
  struggling_engines: Array<{ engine_id: string; score: number }>;
}

/** An optimization suggestion generated by the AGI subsystem */
export interface Suggestion {
  /** Engine ID this suggestion applies to */
  engine_id: string;
  /** Why the AGI system flagged this engine */
  reason: string;
  /** Current quality score */
  current_score: number;
  /** Recommended action to improve the engine */
  recommended_action: string;
}

// ── Client implementation ────────────────────────────────────────────────────

/**
 * SDK client for AGI (self-improvement) operations — the feedback loop that
 * makes Echo engines smarter over time through quality signals, automatic
 * retraining, and optimization suggestions.
 *
 * @example
 * ```ts
 * const agi = new AGIClient({ apiKey: 'my-key' });
 *
 * // Submit feedback after querying an engine
 * await agi.feedback({
 *   engine_id: 'tax-depreciation-v3',
 *   query: 'What is MACRS depreciation?',
 *   quality_score: 0.95,
 *   feedback_text: 'Accurate and well-cited response'
 * });
 *
 * // Check what needs improvement
 * const suggestions = await agi.suggestions();
 * for (const s of suggestions) {
 *   console.log(`${s.engine_id}: ${s.recommended_action} (score: ${s.current_score})`);
 * }
 *
 * // Monitor learning rate
 * const rate = await agi.learningRate();
 * console.log(`Daily improvement: ${rate.daily_improvement}%`);
 * ```
 */
export class AGIClient {
  private client: EchoHttpClient;

  constructor(config: AGIConfig) {
    const clientConfig: EchoClientConfig = {
      apiKey: config.apiKey,
      gatewayUrl: config.baseUrl,
    };
    this.client = new EchoHttpClient(clientConfig);
  }

  /**
   * Get the current AGI subsystem status — aggregate feedback counts,
   * average quality scores, and retrain history.
   * @returns AGI status with feedback and retrain statistics
   */
  async status(): Promise<AGIStatus> {
    return this.client.request<AGIStatus>('/agi/status');
  }

  /**
   * Submit quality feedback for an engine response.
   * When quality drops below threshold, an automatic retrain may be triggered.
   *
   * @param request - Feedback data including engine_id, quality_score, and optional context
   * @returns Whether the feedback was recorded and if auto-retrain was triggered
   *
   * @example
   * ```ts
   * const result = await agi.feedback({
   *   engine_id: 'legal-contracts-v2',
   *   quality_score: 0.4,
   *   feedback_text: 'Missed key clause about indemnification'
   * });
   * if (result.auto_retrain_triggered) {
   *   console.log('Auto-retrain triggered due to low quality score');
   * }
   * ```
   */
  async feedback(
    request: FeedbackRequest,
  ): Promise<{ recorded: boolean; auto_retrain_triggered: boolean }> {
    const body: Record<string, unknown> = {
      engine_id: request.engine_id,
      quality_score: request.quality_score,
    };
    if (request.query !== undefined) body.query = request.query;
    if (request.feedback_text !== undefined) body.feedback_text = request.feedback_text;

    return this.client.request<{ recorded: boolean; auto_retrain_triggered: boolean }>(
      '/agi/feedback',
      {
        method: 'POST',
        body,
      },
    );
  }

  /**
   * Manually trigger a retrain job for a specific engine.
   * Use this when you know an engine needs improvement but automatic
   * retraining hasn't kicked in.
   *
   * @param engineId - Engine ID to retrain
   * @param reason - Optional reason for the retrain (logged for audit)
   * @returns Retrain job ID and initial status
   */
  async retrain(
    engineId: string,
    reason?: string,
  ): Promise<{ job_id: string; status: string }> {
    const body: Record<string, unknown> = { engine_id: engineId };
    if (reason !== undefined) body.reason = reason;

    return this.client.request<{ job_id: string; status: string }>('/agi/retrain', {
      method: 'POST',
      body,
    });
  }

  /**
   * Get learning rate analytics — how fast engines are improving,
   * which ones are excelling, and which ones are struggling.
   *
   * @returns Learning rate data with trends and per-engine breakdowns
   *
   * @example
   * ```ts
   * const rate = await agi.learningRate();
   * console.log(`Trend: ${rate.weekly_trend}`);
   * rate.struggling_engines.forEach(e => {
   *   console.log(`  ${e.engine_id} needs attention (score: ${e.score})`);
   * });
   * ```
   */
  async learningRate(): Promise<LearningRate> {
    return this.client.request<LearningRate>('/agi/learning-rate');
  }

  /**
   * Get AI-generated optimization suggestions for underperforming engines.
   * The AGI subsystem analyzes feedback patterns and proposes concrete
   * actions to improve engine quality.
   *
   * @returns Array of suggestions with engine IDs, reasons, and recommended actions
   *
   * @example
   * ```ts
   * const suggestions = await agi.suggestions();
   * for (const s of suggestions) {
   *   if (s.current_score < 0.5) {
   *     // Auto-retrain critically underperforming engines
   *     await agi.retrain(s.engine_id, s.reason);
   *   }
   * }
   * ```
   */
  async suggestions(): Promise<Suggestion[]> {
    return this.client.request<Suggestion[]>('/agi/suggestions');
  }
}

export { AGIClient as default };
